site_name: OctoLearn
site_description: The Enterprise-Grade AutoML Orchestrator for Python.
site_url: https://octolearn.vercel.app/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - header.autohide
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: slate
      primary: custom
      accent: custom
  font: false # Disable default font to use custom CSS Shantell Sans

nav:
  - '🏠 Home': index.md
  - '🏗️ Architecture': architecture.md
  - '📖 User Guide': guide.md
  - '🧪 Testing': testing.md

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GhulamMuhammadNabeel/OctoLearn
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/ghulam-muhammad-nabeel-a6997a313/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/nabeelqureshitiii
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repositories/ghulammuhammadnabeel
    - icon: fontawesome/brands/google
      link: https://www.google.com/search?q=Ghulam+Muhammad+Nabeel
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ghulammuhammadnabeel

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
